editing/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.edition, name='edition'),
    path('listo/', views.edited, name='edited'),
    path('agencia/crear', views.create_agency, name='create_agency'),
    path('rutas/crear', views.create_route, name='create_route'),
    path('stop/crear', views.create_stop, name='create_stop'),
    path('agencia/lista', views.list_agency, name='list_agency'),
    path('ruta/lista', views.list_route, name='list_route'),
    path('stop/lista', views.list_stop, name='list_stop'),
    path('agencia/eliminar/<agency_id>/', views.delete_agency, name='delete_agency'),
    path('agencia/editar/<int:agency_id>/', views.edit_agency, name='edit_agency'),
    path('ruta/editar/<int:route_id>/', views.edit_route, name='edit_route'),
    path('ruta/eliminar/<route_id>/', views.delete_route, name='delete_route'),
    # path('rutas/<route_id>/', views.route, name='route')
]

editor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('website.urls'), name='index'),
    path('datos/', include('viewing.urls'), name='datos'),
    path('edicion/', include('editing.urls'), name='edicion'),
    path('reportes/', include('reporting.urls'), name='reportes'),
    path('exportacion/', include('exporting.urls'), name='exportacion'),
    path('importacion/', include('importing.urls'), name='importacion'),
    path('perfil/', include('users.urls'), name='perfil'),
    path('gtfs/', include('gtfs.urls'), name='gtfs'),
]

# URLS para el editor de GTFS
# editorbuses.cr/gtfs/<version-gtfs>/editar/

gtfs/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.feeds, name='feeds'),
    path('<str:version_gtfs>/', views.feed, name='feed'),
    path('<str:version_gtfs>/editar/', views.edit, name='edit'),
]

editing/models.py
from django.db import models

# Create your models here.

gtfs/models.py
from django.contrib.gis.db import models


# Models for the system


class Company(models.Model):
    """A company that provides transit service.

    This company may provide service for multiple agencies.
    TODO: add PhoneNumberField
    """

    company_id = models.CharField(max_length=255, blank=True, primary_key=True)
    name = models.CharField(max_length=127)
    address = models.CharField(max_length=1024)
    phone = models.CharField(max_length=255)
    email = models.EmailField(max_length=254)
    website = models.URLField(blank=True)
    logo = models.ImageField(upload_to="logos/", blank=True)

    def __str__(self):
        return self.name


class Feed(models.Model):
    """Container of the GTFS files.

    TODO: a function to check if there are changes in the feed.
    TODO: a function to create the feed_id from the date of creation.
    TODO: evaluate if feed_info is what we want here (creo que no)
    """

    feed_id = models.CharField(max_length=255, blank=True, primary_key=True)
    company_id = models.ForeignKey("Company", null=True, on_delete=models.SET_NULL)
    zip_file = models.FileField(upload_to="feeds/")
    created_at = models.DateTimeField(auto_now_add=True)
    is_current = models.BooleanField(default=True)
    in_edition = models.BooleanField(default=False)

    def __str__(self):
        """Returns a name for the feed with a version number. The
        version number is the date and time when the feed was created."""
        x = self.created_at
        return f"GTFS v{x.year}.{x.month}.{x.day}.{x.hour}.{x.minute}"


# Models for the GTFS feed


class Agency(models.Model):
    """One or more transit agencies that provide the data in this feed.
    Maps to agency.txt in the GTFS feed.
    """

    agency_id = models.CharField(
        primary_key=True,
        max_length=127,
        help_text="Identificador único de la agencia de transportes.",
    )
    name = models.CharField(
        max_length=255, help_text="Nombre completo de la agencia de transportes."
    )
    url = models.URLField(help_text="URL de la agencia de transportes.")
    timezone = models.CharField(
        max_length=255, help_text="Zona horaria de la agencia de transportes."
    )
    lang = models.CharField(
        max_length=2, help_text="Código ISO 639-1 de idioma primario."
    )
    phone = models.CharField(
        max_length=255, help_text="Número de teléfono."
    )
    fare_url = models.URLField(
        help_text="URL para la compra de tiquetes en línea."
    )
    email = models.EmailField(
        help_text="Correo electrónico de servicio al cliente.",
    )

    class Meta:
        verbose_name = "agency"
        verbose_name_plural = "agencies"

    def __str__(self):
        return self.name


class Stop(models.Model):
    """A stop or station
    Maps to stops.txt in the GTFS feed.
    """

    stop_id = models.CharField(
        primary_key=True,
        max_length=255,
        db_index=True,
        help_text="Identificador único de una parada o estación.",
    )
    code = models.CharField(max_length=127, blank=True, null=True)
    name = models.CharField(max_length=255, help_text="Nombre de la parada.")
    desc = models.CharField(
        "description", max_length=511, blank=True, null=True, help_text="Descripción de la parada."
    )
    lat = models.DecimalField(
        max_digits=22,
        decimal_places=16,
        help_text="Latitud WGS 84 de la parada o estación.",
    )
    lon = models.DecimalField(
        max_digits=22,
        decimal_places=16,
        help_text="Longitud WGS 84 de la parada o estación.",
    )
    point = models.PointField(
        blank=True, null=True, help_text="Ubicación de la parada o estación."
    )
    zone_id = models.ForeignKey(
        "Zone",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        help_text="Zona tarifaria para esta parada.",
    )
    url = models.URLField(blank=True, help_text="URL de la parada.")
    location_type = models.CharField(
        max_length=1,
        blank=True,
        choices=(("0", "Parada"), ("1", "Estación")),
        help_text="¿Es una parada o una estación?",
    )
    parent_station = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        help_text="La estación asociada con la parada.",
    )
    wheelchair_boarding = models.CharField(
        max_length=1,
        null=True,
        blank=True,
        choices=(
            ("0", "No hay información."),
            ("1", "Abordaje parcial de silla de ruedas."),
            ("2", "Las sillas de ruedas no pueden subir."),
        ),
        help_text="¿Es posible subir al transporte en silla de ruedas?",
    )

    def __str__(self):
        return self.stop_id + ": " + self.name


class Route(models.Model):
    """A transit route
    Maps to route.txt in the GTFS feed.
    """

    route_id = models.CharField(
        primary_key=True,
        max_length=64,
        db_index=True,
        help_text="Identificador único de la ruta.",
    )
    agency = models.ForeignKey(
        "Agency",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        help_text="Agencia de transportes de la ruta.",
    )
    short_name = models.CharField(max_length=63, help_text="Nombre corto de la ruta.")
    long_name = models.CharField(max_length=255, help_text="Nombre largo de la ruta.")
    desc = models.TextField(
        "description", blank=True, help_text="Descripción detallada de la ruta."
    )
    route_type = models.IntegerField(
        "route type",
        default=3,
        choices=(
            (0, "Tranvía o tren ligero."),
            (1, "Subterráneo o metro."),
            (2, "Ferrocarril."),
            (3, "Bus."),
            (4, "Ferry."),
            (5, "Teleférico."),
            (6, "Góndola."),
            (7, "Funicular."),
        ),
        help_text="Medio de transporte usado en la ruta.",
    )
    url = models.CharField(
        max_length=64, blank=True, help_text="Página web de la ruta."
    )
    color = models.CharField(
        max_length=6, blank=True, help_text="Color de la ruta en código hexadecimal."
    )
    text_color = models.CharField(
        max_length=6,
        blank=True,
        help_text="Color del texto de ruta en código hexadecimal.",
    )
    sort_order = models.PositiveIntegerField(
        blank=True, null=True,
        help_text="Ordena las rutas en una forma apropiada para la presentación a usuarios. Menor número es mayor prioridad."
    )

    def __str__(self):
        return f"{self.short_name}: {self.long_name}"


class Trip(models.Model):
    """A trip along a route
    This implements trips.txt in the GTFS feed
    """

    route = models.ForeignKey("Route", on_delete=models.CASCADE)
    service = models.ForeignKey(
        "Calendar", null=True, blank=True, on_delete=models.SET_NULL
    )
    trip_id = models.CharField(
        primary_key=True,
        max_length=255,
        db_index=True,
        help_text="Indentificador único de viaje.",
    )
    headsign = models.CharField(
        max_length=255,
        blank=True,
        help_text="Identificación de destino para pasajeros.",
    )
    short_name = models.CharField(
        max_length=63,
        blank=True,
        help_text="Nombre corto utilizado en horarios y letreros.",
    )
    departure_time = models.TimeField(
        auto_now=False,
        auto_now_add=False,
        default=None,
        null=True,
        blank=True,
        help_text="Hora de salida del viaje (ELIMINAR).",
    )
    arrival_time = models.TimeField(
        auto_now=False,
        auto_now_add=False,
        default=None,
        null=True,
        blank=True,
        help_text="Hora de llegada del viaje (ELIMINAR).",
    )
    duration = models.PositiveIntegerField(
        default=None, null=True, blank=True, help_text="Minutos de duración del viaje."
    )
    direction = models.CharField(
        max_length=1,
        blank=True,
        choices=(("0", "Hacia San José."), ("1", "Desde San José.")),
        help_text="Dirección para rutas en dos sentidos.",
    )
    block = models.CharField(
        max_length=63, null=True, blank=True,
        help_text="Block of sequential trips that this trip belongs to."
    )
    shape = models.CharField(
        max_length=127,
        null=True, blank=True,
        help_text="Forma de la ruta.",
    )
    geoshape = models.ForeignKey(
        "GeoShape",
        null=True, blank=True,
        on_delete=models.SET_NULL,
        help_text="Forma de la ruta (geometría de GeoDjango).",
    )
    wheelchair_accessible = models.CharField(
        max_length=1,
        blank=True,
        choices=(
            ("0", "No hay información."),
            ("1", "Hay espacio para el transporte de sillas de ruedas."),
            ("2", "No hay espacio para el transporte de sillas de ruedas."),
        ),
        help_text="¿Hay espacio para el transporte de sillas de ruedas?",
    )
    bikes_allowed = models.CharField(
        max_length=1,
        blank=True,
        choices=(
            ("0", "No hay información."),
            ("1", "Hay espacio para el transporte de bicicletas."),
            ("2", "No hay espacio para el transporte de bicicletas."),
        ),
        help_text="¿Hay espacio para el transporte de bicicletas?",
    )

    class Meta:
        verbose_name = "trip"
        verbose_name_plural = "trips"

    def __str__(self):
        return self.trip_id


class StopTime(models.Model):
    """A specific stop on a route on a trip.
    This implements stop_times.txt in the GTFS feed
    """

    trip = models.ForeignKey("Trip", on_delete=models.CASCADE)
    stop = models.ForeignKey("Stop", on_delete=models.CASCADE)
    arrival_time = models.TimeField(
        default=None,
        null=True,
        blank=True,
        help_text="Hora de llegada. Debe configurarse para las últimas paradas del viaje.",
    )

editing/views.py
from django.shortcuts import render, redirect
from gtfs.models import Agency, Route, Stop, Zone

# Create your views here.


def edition(request):
    return render(request, "edition.html")


def create_agency(request):
    if request.method == "POST":
        agency = Agency(
            agency_id=request.POST["agency_id"],
            name=request.POST["agency_name"],
            url=request.POST["agency_url"],
            timezone=request.POST["agency_timezone"],
            lang=request.POST["agency_lang"],
            phone=request.POST["agency_phone"],
            fare_url=request.POST["agency_fare_url"],
            email=request.POST["agency_email"],
        )
        agency.save()
        return redirect("edited")
    else:
        return render(request, "agency.html")


def create_route(request):
    if request.method == "POST":
        agency = Agency.objects.get(agency_id=request.POST["route_agency"])
        route = Route(
            route_id=request.POST["route_id"],
            agency=agency,
            short_name=request.POST["route_short_name"],
            long_name=request.POST["route_long_name"],
            desc=request.POST["route_desc"],
            route_type=request.POST["route_type"],
            url=request.POST["route_url"],
            color=request.POST["route_color"][1:7],
            text_color=request.POST["route_text_color"][1:7],
        )
        route.save()
        return redirect("edited")
    else:
        agencies = Agency.objects.all()
        route_type_choices = Route.ROUTE_TYPE_CHOICES
        context = {
            "agencies": agencies,
            "route_type_choices": route_type_choices,
        }
        return render(request, "routes.html", context)

def create_stop(request):
    if request.method == "POST":
        # Handle the POST request as before
        zone = Zone.objects.get(zone_id=request.POST["stop_zone"])
        stop = Stop(
            stop_id=request.POST["stop_id"],
            name=request.POST["stop_name"],
            desc=request.POST["stop_desc"],
            lat=request.POST["stop_lat"],
            lon=request.POST["stop_lon"],
            loc=request.POST["stop_loc"],
            zone=zone,
            url=request.POST["stop_url"],
            location_type=request.POST["stop_location_type"],
            parent_station=request.POST["stop_parent_station"],
            wheelchair_boarding=request.POST["stop_wheelchair_boarding"],
        )
        stop.save()
        return redirect("edited")
    else:
        return render(request, "stop.html")

def list_agency(request):
    agencies = Agency.objects.all()
    return render(request, 'list_agency.html', {'agencies': agencies})

def list_route(request):
    routes = Route.objects.all()
    return render(request, 'list_route.html', {'routes': routes})

def list_stop(request):
    stops = Stop.objects.all()
    return render(request, 'list_stop.html', {'stops': stops})

def delete_agency(request, agency_id):
    agency = Agency.objects.get(agency_id=agency_id)
    agency.delete()
    return redirect("list_agency")

def delete_route(request, route_id):
    route = Route.objects.get(Route, route_id=route_id)
    route.delete()
    return redirect("list_route")

def edit_agency(request, agency_id):
    agency = Agency.objects.get(agency_id=agency_id)
    if request.method == "POST":
        agency.name = request.POST["agency_name"]
        agency.url = request.POST["agency_url"]
        agency.timezone = request.POST["agency_timezone"]
        agency.lang = request.POST["agency_lang"]
        agency.phone = request.POST["agency_phone"]
        agency.fare_url = request.POST["agency_fare_url"]
        agency.email = request.POST["agency_email"]
        agency.save()
        return redirect("edited")
    else:
        context = {"agency": agency}
        return render(request, "edit_agency.html", context)

def edit_route(request, route_id):
    route = Route.objects.get(route_id=route_id)
    agencies = Agency.objects.all()
    route_type_choices = Route.ROUTE_TYPE_CHOICES  # Mover esto fuera de la condición

    if request.method == "POST":
        # Procesar el formulario POST y guardar los cambios en la ruta
        route.short_name = request.POST["route_short_name"]
        route.long_name = request.POST["route_long_name"]
        route.desc = request.POST["route_desc"]
        route.route_type = request.POST["route_type"]
        route.url = request.POST["route_url"]
        route.color = request.POST["route_color"][1:7]
        route.text_color = request.POST["route_text_color"][1:7]

        # Obtener la agencia seleccionada y asignarla a la ruta
        agency_id = request.POST["route_agency"]
        agency = Agency.objects.get(agency_id=agency_id)
        route.agency = agency

        route.save()
        return redirect("edited")
    else:
        # Renderizar el formulario de edición con la información actual y las agencias disponibles
        context = {"route": route, "agencies": agencies, "route_type_choices": route_type_choices}
        return render(request, "edit_route.html", context)


def edited(request):
    return render(request, "edited.html")

editing/templates/agency.html
{% extends 'base.html' %}

{% load static %}

{% block main %}

<h1>Edición</h1>

<p>Datos GTFS editables por usuarios con los permisos.</p>

<h2>Agencia de transportes</h2>

<p>Llenar la información a continuación.</p>

<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label for="agency_id" class="form-label">Identificador de la agencia</label>
        <input type="text" class="form-control" name="agency_id" id="agency_id">
    </div>
    <div class="mb-3">
        <label for="agency_name" class="form-label">Nombre de la agencia</label>
        <input type="text" class="form-control" name="agency_name" id="agency_name">
    </div>
    <div class="mb-3">
        <label for="agency_url" class="form-label">Dirección web de la agencia</label>
        <input type="text" class="form-control" name="agency_url" id="agency_url" pattern="https?://.+">
    </div>
    <div class="mb-3">
        <label for="agency_timezone" class="form-label">Zona horaria de la agencia</label>
        <input type="text" class="form-control" name="agency_timezone" id="agency_timezone">
    </div>
    <div class="mb-3">
        <label for="agency_lang" class="form-label">Idioma de la agencia</label>
        <input type="text" class="form-control" name="agency_lang" id="agency_lang">
    </div>
    <div class="mb-3">
        <label for="agency_phone" class="form-label">Teléfono de la agencia</label>
        <input type="text" class="form-control" name="agency_phone" id="agency_phone">
    </div>
    <div class="mb-3">
        <label for="agency_fare_url" class="form-label">Sitio con tarifas de la agencia</label>
        <input type="text" class="form-control" name="agency_fare_url" id="agency_fare_url">
    </div>
    <div class="mb-3">
        <label for="agency_email" class="form-label">Correo electrónico de la agencia</label>
        <input type="email" class="form-control" name="agency_email" id="agency_email">
    </div>
    <div class="mb-3">
        <button type="submit" class="btn btn-primary">Enviar</button>
    </div>    
</form>

{% endblock %}

editing/templates/edit_agency.html
{% extends 'base.html' %}

{% load static %}

{% block main %}

<h1>Edición</h1>

<p>Datos GTFS editables por usuarios con los permisos.</p>

<h2>Agencia de transportes</h2>

<p>Editar la información a continuación.</p>

<form method="POST" action="{% url 'edit_agency' agency.agency_id %}">
    {% csrf_token %}
    <div class="mb-3">
        <label for="agency_id" class="form-label">Identificador de la agencia</label>
        <input type="text" class="form-control" name="agency_id" id="agency_id" value="{{ agency.agency_id }}" readonly>
    </div>
    <div class="mb-3">
        <label for="agency_name" class="form-label">Nombre de la agencia</label>
        <input type="text" class="form-control" name="agency_name" id="agency_name" value="{{ agency.name }}">
    </div>
    <div class="mb-3">
        <label for="agency_url" class="form-label">Dirección web de la agencia</label>
        <input type="text" class="form-control" name="agency_url" id="agency_url" pattern="https?://.+" value="{{ agency.url }}">
    </div>
    <div class="mb-3">
        <label for="agency_timezone" class="form-label">Zona horaria de la agencia</label>
        <input type="text" class="form-control" name="agency_timezone" id="agency_timezone" value="{{ agency.timezone }}">
    </div>
    <div class="mb-3">
        <label for="agency_lang" class="form-label">Idioma de la agencia</label>
        <input type="text" class="form-control" name="agency_lang" id="agency_lang" value="{{ agency.lang }}">
    </div>
    <div class="mb-3">
        <label for="agency_phone" class="form-label">Teléfono de la agencia</label>
        <input type="text" class="form-control" name="agency_phone" id="agency_phone" value="{{ agency.phone }}">
    </div>
    <div class="mb-3">
        <label for="agency_fare_url" class="form-label">Sitio con tarifas de la agencia</label>
        <input type="text" class="form-control" name="agency_fare_url" id="agency_fare_url" value="{{ agency.fare_url }}">
    </div>
    <div class="mb-3">
        <label for="agency_email" class="form-label">Correo electrónico de la agencia</label>
        <input type="email" class="form-control" name="agency_email" id="agency_email" value="{{ agency.email }}">
    </div>
    <div class="mb-3">
        <button type="submit" class="btn btn-primary">Enviar</button>
    </div>    
</form>

{% endblock %}

editing/templates/edit_route.html
{% extends 'base.html' %}

{% load static %}

{% block main %}

  <h1>Edición</h1>

  <p>Datos GTFS editables por usuarios con los permisos.</p>

  <h2>Rutas de transportes</h2>

  <p>Llenar la información a continuación.</p>

  <form method="POST">
    {% csrf_token %}
    
    <div class="mb-3">
      <label for="route_id" class="form-label">Identificador de la ruta</label>
      <input type="text" class="form-control" name="route_id" id="route_id" value="{{ route.route_id }}" required>
    </div>

    <div class="mb-3">
      <label for="route_agency">Escoje la agencia de la ruta</label>
      <select name="route_agency">
          {% for agency in agencies %}
              <option value="{{ agency.agency_id }}" {% if agency == route.agency %}selected{% endif %}>{{ agency.name }}</option>
          {% endfor %}
      </select>
  </div>

    <div class="mb-3">
      <label for="route_short_name" class="form-label">Nombre corto de la ruta</label>
      <input type="text" class="form-control" name="route_short_name" id="route_short_name" value="{{ route.short_name }}" required>
    </div>

    <div class="mb-3">
      <label for="route_long_name" class="form-label">Nombre largo de la ruta</label>
      <input type="text" class="form-control" name="route_long_name" id="route_long_name" value="{{ route.long_name }}" required>
    </div>

    <div class="mb-3">
      <label for="route_desc" class="form-label">Descripción detallada de la ruta</label>
      <textarea name="route_desc" id="route_desc" cols="30" rows="4" required>{{ route.desc }}</textarea>
    </div>

    <div class="mb-3">
      <label for="route_type">Tipo de ruta</label>
      <select name="route_type">
        {% for route_type in route_type_choices %}
          <option value="{{ route_type.0 }}" {% if route.route_type == route_type.0 %} selected {% endif %}>{{ route_type.1 }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="mb-3">
      <label for="route_url" class="form-label">Página web de la ruta</label>
      <input type="url" class="form-control" name="route_url" id="route_url" value="{{ route.url }}" required>
    </div>

    <div class="mb-3">
      <label for="route_color" class="form-label">Color de la ruta en código hexadecimal</label>
      <input type="color" class="form-control" name="route_color" id="route_color" value="{{ route.color }}">
    </div>

    <div class="mb-3">
      <label for="route_text_color" class="form-label">Color del texto de ruta en código hexadecimal</label>
      <input type="color" class="form-control" name="route_text_color" id="route_text_color" value="{{ route.text_color }}">
    </div>

    <div class="mb-3">
      <button type="submit" class="btn btn-primary">Enviar</button>
    </div>
  </form>

{% endblock %}

editing/templates/edited.html
{% extends 'base.html' %}

{% load static %}

{% block main %}

<p>Sí, se agregó el registro</p>

{% endblock %}

editing/templates/edition.html
{% extends 'base.html' %}

{% load static %}

{% block main %}

<p>
    Seleccione la tabla que quiere agregar:
</p>

<ul>
    <li><a href="{% url 'create_agency' %}">Agencia</a></li>
    <li><a href="{% url 'create_route' %}">Rutas</a></li>
    <li><a href="{% url 'create_stop' %}">Paradas</a></li>
</ul>

<br>

<p>
    Seleccione la tabla que quiere eliminar o editar:
</p>

<ul>
    <li><a href="{% url 'list_agency' %}">Agencia</a></li>
    <li><a href="{% url 'list_route' %}">Rutas</a></li>
    <li><a href="{% url 'create_stop' %}">Paradas</a></li>
</ul>

{% endblock %}

editing/templates/list_agency.html
{% extends 'base.html' %}

{% load static %}

{% block main %}

  <h1>Listado de Agencias</h1>
  {% csrf_token %}
  <table class="table">
    <thead>
      <tr>
        <th>ID de Agencia</th>
        <th>Nombre</th>
        <th>URL</th>
        <th>Zona Horaria</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for agency in agencies %}
        <tr>
          <td>{{ agency.agency_id }}</td>
          <td>{{ agency.name }}</td>
          <td>{{ agency.url }}</td>
          <td>{{ agency.timezone }}</td>
          <td>
            <a href="{% url 'delete_agency' agency.agency_id %}" class="btn btn-danger">Eliminar</a>
            <a href="{% url 'edit_agency' agency.agency_id %}" class="btn btn-primary">Editar</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

editing/templates/list_route.html
{% extends 'base.html' %}

{% load static %}

{% block main %}

  <h1>Listado de Rutas</h1>
  {% csrf_token %}
  <table class="table">
    <thead>
      <tr>
        <th>ID de Ruta</th>
        <th>Nombre Corto</th>
        <th>Nombre Largo</th>
        <th>Tipo de Ruta</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for route in routes %}
        <tr>
          <td>{{ route.route_id }}</td>
          <td>{{ route.short_name }}</td>
          <td>{{ route.long_name }}</td>
          <td>{{ route.get_route_type_display }}</td>
          <td>
            <a href="{% url 'delete_route' route.route_id %}" class="btn btn-danger">Eliminar</a>
            <a href="{% url 'edit_route' route.route_id %}" class="btn btn-primary">Editar</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

editing/templates/list_stop.html
{% extends 'base.html' %}

{% load static %}

{% block main %}
  <h1>Listado de Paradas</h1>
  {% csrf_token %}
  <table class="table">
    <thead>
      <tr>
        <th>ID de Parada</th>
        <th>Nombre</th>
        <th>Descripción</th>
      </tr>
    </thead>
    <tbody>
      {% for stop in stops %}
        <tr>
          <td>{{ stop.stop_id }}</td>
          <td>{{ stop.name }}</td>
          <td>{{ stop.desc }}</td>
          <td>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

editing/templates/routes.html
{% extends 'base.html' %}

{% load static %}

{% block main %}

<h1>Edición</h1>

<p>Datos GTFS editables por usuarios con los permisos.</p>

<h2>Rutas de transportes</h2>

<p>Llenar la información a continuación.</p>

<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label for="route_id" class="form-label">Identificador de la ruta</label>
        <input type="text" class="form-control" name="route_id" id="route_id" required>
    </div>

    <div class="mb-3">
        <label for="route_agency">Escoje la agencia de la ruta</label>
        <select name="route_agency">
            {% for agency in agencies %}
            <option value="{{ agency.agency_id }}">{{ agency.name }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="mb-3">
        <label for="route_short_name" class="form-label">Nombre corto de la ruta</label>
        <input type="text" class="form-control" name="route_short_name" id="route_short_name" required>
    </div>
    <div class="mb-3">
        <label for="route_long_name" class="form-label">Nombre largo de la ruta</label>
        <input type="text" class="form-control" name="route_long_name" id="route_long_name" required>
    </div>
    <div class="mb-3">
        <label for="route_desc" class="form-label">Descripción detallada de la ruta</label>
        <textarea name="route_desc" id="route_desc" cols="30" rows="4" required></textarea>
    </div>

    <div class="mb-3">
        <label for="route_type">Tipo de ruta</label>
        <select name="route_type">
            {% for route_type in route_type_choices %}
            <option value="{{ route_type.0 }}">{{ route_type.1 }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="mb-3">
        <label for="route_url" class="form-label">Página web de la ruta</label>
        <input type="url" class="form-control" name="route_url" id="route_url" required>
    </div>

    <div class="mb-3">
        <label for="route_color" class="form-label">Color de la ruta en código hexadecimal</label>
        <input type="color" class="form-control" name="route_color" id="route_color">
    </div>

    <div class="mb-3">
        <label for="route_text_color" class="form-label">Color del texto de ruta en código hexadecimal</label>
        <input type="color" class="form-control" name="route_text_color" id="route_text_color">
    </div>

    <div class="mb-3">
        <button type="submit" class="btn btn-primary">Enviar</button>
    </div>    
</form>

{% endblock %}